# Makefile.defs for clamav-realtime, Gentoo Linux specs.

OS=$(shell uname)
DESTDIR="${D}"
PREFIX=/usr/bin
PIXMAPS=/usr/share/pixmaps
APPS=/usr/share/applications
DOCDIR=/usr/share/doc
DOCFILES=ChangeLog Copying BUGS INSTALL README THANKS TODO
